# theme: jekyll-theme-dinky
theme: jekyll-theme-cayman
google_analytics: ['UA-128916623-7']
title: [Getting Started with AWS CDK from scratch]
description: [Getting Started with AWS CDK from scratch]
github:
  home_url: https://rupeshtiwari.com